### ISSUE TITLE
[Request] Add posibility to hide plugins

### ISSUE THREAD

**Issue by vojacekj** [SteamDeckHomebrew/decky-loader#403] opened 2023-03-25 08:54 UTC
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] This is not a request for a plugin

### Feature Request Description

Some plugins are a type of set-it-and-forget-it plugins, so it would be pretty useful to have the possibility to simply hide such plugins from the menu to save some space and declutter.

### Further Description

It could be added next to existing options to reload and uninstall plugin

**Comment by PartyWumpus** [comment] 2023-03-25 09:06
Duplicate of #317, which is marked as "help wanted", so if you're able to add this functionality yourself it would likely be accepted, but the dev team is not currently planning to work on it.

**Closed** 2023-03-25 10:42 UTC
Labels: feature request
