### ISSUE TITLE
Will Decky support be added to the new ... menu for the Windows menu in Steam big picture?

### ISSUE THREAD

**Issue by jazir5** [SteamDeckHomebrew/decky-loader#248] opened 2022-11-03 23:53 UTC
With the new big picture update coming to Windows, they are adding the menu which can be triggered with the ... button on Windows, just like it can on Steam OS. Will Decky loader be updated to support the menu on Windows? Would love to be able to use the plugins with the Windows version.

**Comment by TrainDoctor** [comment] 2022-11-03 23:56
No, no support for windows is planned. Forks are always welcome but this is a wontfix that the team has no desire to even approach. Sorry to give you bad news.

**Comment by Epictek** [comment] 2022-11-03 23:56
Duplicate of #237

**Closed** 2022-11-03 23:56 UTC

**Comment by shawny43** [comment] 2023-03-25 03:05
There an app call SteamFriendsPatcher where they able to patch stuff. Maybe you can talk to these developpers for some cases.
