### ISSUE TITLE
Issue on SteamDeck 3.3.2 Stable - Decky-Loader doesn't survive reboot

### ISSUE THREAD

**Issue by fangme** [SteamDeckHomebrew/decky-loader#247] opened 2022-11-03 17:01 UTC
Issue on SteamDeck 3.3.2 Stable - Decky-Loader doesn't survive reboot.  Worked until I shut the system down, rebooted, and decky-loader doesn't seem to load.

Does something need to be done in desktop mode to get it to load when booting?

**Comment by TrainDoctor** [comment] 2022-11-03 23:56
What version of decky loader are you using? Try updating to the latest pre-release.

**Comment by fangme** [comment] 2022-11-04 11:45
How does one tell?  The only version referenced on the github page is V2.2.7, which is only described as the "latest".  Generated 19 days ago.  Since I installed using the curl line which is supposed " the latest stable version", I'd assume thats the version I have, since I downloaded/installed on 10/29/22.  I do see that there are more commits, but not a new "version".  Meanwhile, I have had 2 different updates - mostly to games, but also to Proton, and other items.

Sorry, this distro of Linux is new/different enough to me I don't recognize what the updates are for to be able to tell if they interfere with anything else or not.

**Comment by rlach** [comment] 2022-11-04 14:58
If you get it to work at least after full reboot you can go into decky => cogwheel => Updates. It will show you "Current Version". The current "current version" is 2.3.1-pre3.

That said on 2.3.1-pre3 if I restart steam client the decky does NOT re-appear for me, on stable branch of Steam. Only full reboot of SD works. I tried restarting steam client few times in hope it randomly works, but it doesn't. I tried full reboot twice and in both cases the decky appeared as expected, and the plugins worked as expected.

**Comment by fangme** [comment] 2022-11-04 15:02
I do a full shutdown, restart the SD, and - no decky.  So I can't check the menu to see what version is loaded or not.  I will try to uninstall it completely, reboot, reinstall - see what happens

**Comment by fangme** [comment] 2022-11-04 15:10
uninstall/reinstall worked after a reboot.  And left the ProtonDB badges plugin in place.   Then did a full shutdown, and startup.  Still running.

Go to settings, General - says current version is 2.2.7, latest version is undefined.  I have the 'Prerelease' channel selected.  Seems I'm NOT seeing the same version as you are rlach.

**Comment by PartyWumpus** [comment] 2022-11-04 16:13
> Go to settings, General - says current version is 2.2.7

2.2.7 is the most recent stable release. 

> The only version referenced on the github page is V2.2.7

if you look in the releases page it'll list all the pre-releases next to the releases https://github.com/SteamDeckHomebrew/decky-loader/releases)

**Comment by iantrich** [comment] 2022-11-04 20:28
Installing the pre-release resolved this issue for me

**Comment by Pixxel123** [comment] 2022-11-06 19:38
Using the latest pre-release, [v2.3.2-pre1](https://github.com/SteamDeckHomebrew/decky-loader/releases/tag/v2.3.2-pre1), Decky is not appearing in QAM on Steam Deck Beta Client.

Log file: 
[backend.log](https://github.com/SteamDeckHomebrew/decky-loader/files/9946695/backend.log)

**Comment by fangme** [comment] 2022-11-10 21:44
Ok - seems just up and down depending on what version of what is loaded.  Beta SteamOS, or Stable SteamOS, beta decky-loader, etc.  Even non-OS updates seem to affect decky-loader.  Just not real consistent unless you flat out don't update anything once it seems to work.

For the time being, I've uninstalled it, and will wait for a more stable release of both SteamOS and decky-loader.

**Comment by TrainDoctor** [comment] 2022-11-10 23:40
Just realized that this is a duplicate of #245. The logs will be used from here but this will be closed for better issue management.

**Closed by TrainDoctor** 2022-11-10 23:40 UTC
Labels: bug
