### ISSUE TITLE
[BUG] vibrant deck and Hltb badges not working any more

### ISSUE THREAD

**Issue by Logge1002** [SteamDeckHomebrew/decky-loader#374] opened 2023-02-18 13:29 UTC
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)

### Bug Report Description

When I start the deck with either stable or prerelease both plugins fail to load with an error that bind couldn’t be performed!

### Expected Behaviour

Both working normally 

### SteamOS version

SteamOs

### Selected Update Channel

Prerelease

### Have you modified the read-only filesystem at any point?

No

### Logs

Decky

**Comment by TrainDoctor** [comment] 2023-02-18 14:14
Duplicate of #371. Leaving opem for now.

**Closed** 2023-02-18 22:47 UTC
Labels: wontfix
