### ISSUE TITLE
PluginLoader high CPU usage in Desktop Mode

### ISSUE THREAD

**Issue by GoaLitiuM** [SteamDeckHomebrew/decky-loader#109] opened 2022-07-05 22:45 UTC
For some reason, the PluginLoader process is still running in background after entering Desktop Mode, and consuming ~12% CPU all the time.

Loader version: v2.0.0-pre
SteamOS: 3.3 beta
Installed plugins:
- Power Tools
- SDH-QuickLaunch

**Comment by TrainDoctor** [comment] 2022-07-05 22:48
> For some reason, the PluginLoader process is still running in background after entering Desktop Mode, and consuming ~12% CPU all the time.

This is due to the nature of the Deck and it's systemd service being triggered by both desktop and gaming modes.
I'll have someone look into this on the team ASAP.

**Comment by AAGaming00** [comment] 2022-07-25 16:31
Unable to reproduce, plugin loader hovers between 0% and 1% in desktop mode.

**Comment by TrainDoctor** [comment] 2022-07-28 02:35
I am closing this issue as "Can't Reproduce". @GoaLitiuM if you have any other logs or information to add please do so and I will re-open the issue.

**Closed by TrainDoctor** 2022-07-28 02:35 UTC
Labels: question
