### ISSUE TITLE
[BUG] Error when opening side panel

### ISSUE THREAD

**Issue by Jademalo** [SteamDeckHomebrew/decky-loader#380] opened 2023-02-23 01:35 UTC
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)

### Bug Report Description

When I open the side bar, a fullscreen error is thrown;

```
Something went wrong while displaying this content. Refresh

Error Reference: Chat_7862870_23da9a2c5e16c465

tab.panel.props.setter[0] is not a function
```

### Expected Behaviour

This error is shown whenever I open the side bar. After seeing it, the decky icon disappears.
Decky is still running in the background, as proton badges are showing in game pages.

I've tried reinstalling Decky, and I'm definitely on 2.5.4

### SteamOS version

SteamOS 3.4.5 20221228.2

### Selected Update Channel

Stable

### Have you modified the read-only filesystem at any point?

No

**Comment by TrainDoctor** [comment] 2023-02-23 01:37
Please try the latest pre-release. It looks like valve did some remote-code updates and changed a few things around. Thanks for the report, @AAGaming00 is actively looking into the issue.

**Comment by Jademalo** [comment] 2023-02-23 01:38
Just tried pre-release, seems to be the same issue. Lemme get the logs now, two secs

**Comment by Zodiaksl** [comment] 2023-02-23 05:04
Same error for me. Came here looking for fix. Understand things take time :)

**Comment by silverosnix** [comment] 2023-02-23 06:55
Having same issue 
Uninstalling until an update it has been fixed 
Unable to access … tab on deck to change settings.

**Comment by TrainDoctor** [comment] 2023-02-23 14:20
@Zodiaksl @silverosnix @sameeris7860 please try latest decky prerelease. Plugins will not work as they will need to update but loader should work.

**Comment by Eolf1337** [comment] 2023-02-23 14:44
> @Zodiaksl @silverosnix @sameeris7860 please try latest decky prerelease. Plugins will not work as they will need to update but loader should work.

Loader works after switching to prerelease but as you said no plugin works.

**Comment by Mizanuto** [comment] 2023-02-23 18:56
Yep, just checked, and @sameeris7860 is probably right, as I got the same fix. Just change to stable client to fix things for now.

**Comment by Zodiaksl** [comment] 2023-02-23 19:52
Pre-release confirmed to work

**Comment by craigz** [comment] 2023-02-23 23:52
pre-release works, but will the plug-ins be updated for this version, or should i wait for a fix in main?

**Comment by TrainDoctor** [comment] 2023-02-23 23:53
Plugin updates will be released when they're authors are available to do so. Until such time I would advise sticking to stable for the time being.

**Comment by DetonationEMS** [comment] 2023-02-25 01:28
Same issue. It has something to do with one of the recent beta updates. A very temporary fix is to set Steam Update Channel to Stable. Next steam update may render decky unusable until there is a fix. 

I'm not a very good coder. I wish I was good enough to help. If I can offer logs, screenshots ect.. lmk. 

Bug aside, keep up the great work. You're making a lot of people happy.

**Comment by mdeguzis** [comment] 2023-02-25 18:30
Pre-release works
```
curl -L https://github.com/SteamDeckHomebrew/decky-loader/raw/main/dist/install_prerelease.sh | sh
```

https://wiki.deckbrew.xyz/en/user-guide/install

**Comment by TrainDoctor** [comment] 2023-02-25 22:22
That reminded me I need to update the install page. Cheers.

**Comment by silverosnix** [comment] 2023-02-28 00:02
Hello all; is there an update on this :) I have not re installed since this bug came up.Thank you for everything Sent from my iPhoneOn Feb 23, 2023, at 4:52 PM, craigz ***@***.***> wrote:﻿
pre-release works, but will the plug-ins be updated for this version, or should i wait for a fix in main?

**Comment by TrainDoctor** [comment] 2023-02-28 00:17
@silverosnix you can switch over to stable and still use plugins. Currently plugins will still need to update to DFL 3.19.1 or later in order to work on beta, preview etc. You can view what plugins have been updated [here](https://github.com/SteamDeckHomebrew/decky-plugin-database/pulls?q=is%3Apr+is%3Aclosed+label%3Aplugin-update+closed%3A%3E2023-02-22).

**Comment by humedoom** [comment] 2023-03-01 04:04
I'm getting:
Something went wrong while displaying this content. Refresh
Error Reference: Shared SteamUI_7834012_9305e8ac929cc2f3
unreachable

**Comment by dragonbra** [comment] 2023-03-01 06:22
> I'm getting: Something went wrong while displaying this content. Refresh Error Reference: Shared SteamUI_7834012_9305e8ac929cc2f3 unreachable

Having similar problem, Error Reference: Shared SteamUI_7834012_xxxxxxxxxxxxx

**Comment by TrainDoctor** [comment] 2023-03-14 05:08
This has been fixed for weeks, but was left open since plugins were breaking. Plugins have been given ample time to update. Closing.

**Closed by TrainDoctor** 2023-03-14 05:08 UTC
Labels: bug
