### ISSUE TITLE
Hang when shutting down until systemd timeout

### ISSUE THREAD

**Issue by Kevadroz** [SteamDeckHomebrew/decky-loader#243] opened 2022-10-31 21:02 UTC
This is probably my fault. but whenever I shut down my system (Arch Linux, Steam Deck) plugin_loader.service does not exit gracefully and I have to either wait the whole timeout or force halt with the power button.

This may be a problem with my installation but anyways, help?

**Comment by TrainDoctor** [comment] 2022-10-31 21:51
We do not provide support for non-SteamOS installs. I suggest re-running the plugin installer as recent issues arose due to a mistake with the configuration of the plugin_loader.service unit to see if that helps. We don't have the scope or the scale to provide support outside of the deck itself.

**Comment by Kevadroz** [comment] 2022-10-31 21:56
Bummer. I configured the service to use SIGKILL on shutdown as a workarround.

**Comment by AAGaming00** [comment] 2022-10-31 23:21
Confirmed on SteamOS.

**Comment by TrainDoctor** [comment] 2022-11-13 02:58
Profiler needed to determine source of timeout issues.

**Comment by desantienator** [comment] 2022-12-04 20:29
@Kevadroz  can you share the workaround please?

**Comment by Kevadroz** [comment] 2022-12-04 21:53
> @Kevadroz can you share the workaround please?

Add "KillSignal=SIGKILL" under [Service].

**Comment by TrainDoctor** [comment] 2022-12-05 03:03
> > @Kevadroz can you share the workaround please?
> 
> Add "KillSignal=SIGKILL" under [Service].

I'll be adding this to the official installer systemd service files and closing the issue as this should resolve the issue for now.

**Closed** 2022-12-05 03:06 UTC
Labels: bug
