### ISSUE TITLE
Can we please have support for writing plugins in something other than python?

### ISSUE THREAD

**Issue by ILOVEPIE** [SteamDeckHomebrew/decky-loader#78] opened 2022-06-06 02:05 UTC
It would make a lot more sense to implement some type of RPC api then have client implementations in various languages that can be used for writing plugins.

**Comment by TrainDoctor** [comment] 2022-06-06 02:59
This is something that's actively planned. It's going to be even better than explicit support of a specific language. it's going to be a system where any language where you can send information through a TCP socket will be supported.
I'll be closing this issue as this is planned to be supported.

**Comment by TrainDoctor** [comment] 2022-06-06 21:27
Re-opening this issue to help foster discussion about how inter-process communication could/will work and usage temp Unix sockets vs other types as two examples of good points brought up by @JohnnyCrazy.

**Comment by ILOVEPIE** [comment] 2022-06-06 21:44
should probably be using some sort of remote procedure call protocol. I
would do this over UNIX sockets simply because it’s going to be more secure.

**Comment by JohnnyCrazy** [comment] 2022-06-06 21:48
I also think UNIX sockets is the way to go. Security aside, it's probably also the fastest and most low-overhead solution.

Regarding security, I'm not 100% sure how UNIX sockets work in detail, but a shared secret which is passed to the plugin server process via its environment variables could work? Would we even need to encrypt the traffic?

**Comment by marios8543** [comment] 2022-06-06 22:05
The loader already uses unix sockets under the hood, for IPC between the loader process and the isolated plugin processes, so in theory you only need to remove the python module run and add a subprocess to an external binary to do this. Most of the work regarding communication is already there

**Comment by ILOVEPIE** [comment] 2022-06-07 17:37
I would say a Remote Procedure Call API over Unix Sockets is the best solution.

**Comment by ILOVEPIE** [comment] 2022-06-07 18:31
Remote Procedure Call would allow methods to be added to the API easily and there are already standard cross-language Remote Procedure Call libraries for communicating over UNIX or TCP/IP sockets. Another advantage is that If a plugin wants to add their own API that other plugins could use a RPC system would easily allow that. One option is [gRPC](https://grpc.io/) which was part of the ProtocolBuffers project.

**Comment by FrogTheFrog** [comment] 2022-08-13 16:31
Hello, I found myself being blocked by the current back-end limitations and for what it's worth I agree with @ILOVEPIE and vote for gRPC.

**Comment by Samuel-B-D** [comment] 2022-09-20 17:33
Just throwing stuff in the air, but another completely different approach could be to allow loading of wasm plugins by integrating wasmtime runtime into decky-loader
https://bytecodealliance.org/articles/wasmtime-1-0-fast-safe-and-production-ready

**Comment by NGnius** [comment] 2022-09-20 17:59
The front-end is a browser so it's already got WASM support baked in. The best course of action would be to provide some sort of API to break out of the browser sandbox (safely) if Decky wanted to go that route. Adding another WASM runtime seems unnecessary unless the CEF version is too out of date or something (it's not; USDPL uses it fine).

But to actually touch on the central discussion: Decky already has support for custom back-ends, with [USDPL](https://github.com/NGnius/usdpl-rs) being the only one that I'm aware of that's used by plugins. It's not using any standard like RPC, and only supports Rust back-ends atm, but it has zero reliance on Decky for back-end activities (aside from actually starting the back-end). The problem is communicating from the front-end to the back-end, and that can be solved just as well by third-party stuff so I don't really think it's necessary for Decky to have it. Obviously I'm biased because I am the third-party in this, but I think leaving it up to the plugins devs is the best course of action when there's no single obvious solution.

**Comment by james2432** [comment] 2022-10-04 07:36
I would advise against using gRPC, you need to use HTTP/2.0 and protobufs have massive overhead vs a tcp socket

**Comment by ILOVEPIE** [comment] 2022-10-04 07:38
GRPC doesn’t have to be over HTTP you can do Protobufs over tcp. Heck valve
uses Protobufs for the source engine networking code.

**Comment by ILOVEPIE** [comment] 2022-10-04 07:39
And nobody said we were using TCP sockets were using UNIX sockets

**Comment by james2432** [comment] 2022-10-04 13:38
then couldn't a random path be passed to the plugin being started in the sysargs?

like /tmp/[some random string here such as a guid]

then the backend would be responsible for opening the unix socket and listening for event/some protocol between decky loader and plugins

**Comment by TrainDoctor** [comment] 2022-11-20 18:39
Work has recently started on support for websockets. Currently python is still needed to start up a plugin's custom backend written in other languages but once websockets are fully implemented, python will no longer be a requirement for interacting with the Decky Loader's backend.

**Comment by AAGaming00** [comment] 2022-12-15 12:20
> Work has recently started on support for websockets. Currently python is still needed to start up a plugin's custom backend written in other languages but once websockets are fully implemented, python will no longer be a requirement for interacting with the Decky Loader's backend.

Clarifying, WebSockets are for communicating between Decky itself and the Decky frontend (and plugin frontends.) This does however solve one of the main things blocking custom non-py backend communication, since it will allow for bidirectional frontend-backend communication.

**Comment by leroycep** [comment] 2023-01-11 20:34
What about using a systemd service for backend services? Take the method used for [running syncthing in game mode in this reddit post](https://www.reddit.com/r/SteamDeck/comments/vocyi5/start_syncthing_automatically_on_steamdeck_even/), and then have plugins communicate using HTTP requests or websockets.

**Comment by TrainDoctor** [comment] 2023-03-05 00:27
This has been largely accomplished through the custom backend effort some time ago. Closing.

**Closed by TrainDoctor** 2023-03-05 00:27 UTC
Labels: help wanted, question, feature request
