### ISSUE TITLE
[BUG] powertools not working with newest pre release. Only shows lines but no options

### ISSUE THREAD

**Issue by Logge1002** [SteamDeckHomebrew/decky-loader#383] opened 2023-02-25 12:07 UTC
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)

### Bug Report Description

With the newest pre release update powertools won’t show any options any more

### Expected Behaviour

Should work but doesnt

### SteamOS version

Steam OS Beta

### Selected Update Channel

Prerelease

### Have you modified the read-only filesystem at any point?

No

### Logs

Nothing

**Comment by TrainDoctor** [comment] 2023-02-25 15:25
Duplicate of #380. Please read the latest release notes.

**Closed by TrainDoctor** 2023-02-25 15:25 UTC
Labels: bug
