### ISSUE TITLE
Decky Loader disappeared on Steam restart

### ISSUE THREAD

**Issue by Pixxel123** [SteamDeckHomebrew/decky-loader#279] opened 2022-12-13 00:42 UTC
I restarted Steam via the Power button menu and Decky Loader disappeared.

**To Reproduce**
1. Hold down the Power button
2. Select Restart Steam

**Version information**
 - SteamOS Version: `Linux mark-steamdeck 5.13.0-valve21.3-1-neptune #1 SMP PREEMPT Mon, 03 Oct 2022 23:17:36 +0000 x86_64 GNU/Linux`
 - Selected Update Channel: `Beta`

**Logs**
[backend.log](https://github.com/SteamDeckHomebrew/decky-loader/files/10213201/backend.log)

**Additional context**
Have you modified the read-only filesystem at any point?  
No.

**Comment by TrainDoctor** [comment] 2022-12-13 00:48
This is a known bug, restart the deck fully and decky will re-inject properly. #278 is a duplicate of this issue, consolidating this under this issue.

**Comment by helliongame** [comment] 2022-12-13 05:34
@TrainDoctor i restarted Steamdeck a lot of times and the issue remain. It dont solve my issue. The Pluggins dont appear and i cant configure them.

**Comment by TrainDoctor** [comment] 2022-12-16 22:19
@helliongame please give the latest pre-release of decky a try, it fixes an issue with the system configured locale that could be related to your issue.

**Closed** 2023-01-17 00:50 UTC
Labels: bug
