### ISSUE TITLE
Install button not working

### ISSUE THREAD

**Issue by Larkietiel** [SteamDeckHomebrew/decky-loader#199] opened 2022-10-04 04:10 UTC
I'm trying to install CSS loader, but when I press the install button it doesn't seem to do anything. It opens the decky menu, but it doesn't show any plugins there. I have restarted my deck several times, and have tried reinstalling Decky.

**Comment by TrainDoctor** [comment] 2022-10-04 04:22
Known issue, duplicate of #197.

**Closed by TrainDoctor** 2022-10-04 04:22 UTC
