### ISSUE TITLE
Decky-loader dissapear after latest Steam Deck beta update

### ISSUE THREAD

**Issue by Lenksi** [SteamDeckHomebrew/decky-loader#198] opened 2022-10-04 04:05 UTC
Hi, everything was working fine until I updated to the new beta update (date 03.10.22) and now the Decky loader is gone from the menu. Reinstalling it didn't help.

**Comment by TrainDoctor** [comment] 2022-10-04 04:21
Known issue, duplicate of #197.

**Closed by TrainDoctor** 2022-10-04 04:21 UTC
