### ISSUE TITLE
[HELP] Can't install decky-loader on Steam Desktop (Fedora)

### ISSUE THREAD

**Issue by AlphaCraft9658** [SteamDeckHomebrew/decky-loader#511] opened 2023-07-23 13:13 UTC
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [x] I have attached logs to this bug report (failure to include logs will mean your issue will not be responded too).

### Bug Report Description

I can't install decky-loader. I have tried to run the different installation methods. While they do finish and are successful, the decky options don't appear in Steam at all. How could I possibly solve this?

### Expected Behaviour

Decky should install and appear in Steam Quick Access Menu.

### SteamOS version

Fedora 38 KDE

### Selected Update Channel

Stable

### Logs

-- No entries --
(Decky doesn't seem to successfully install the plugin-loader service.)

**Comment by PartyWumpus** [comment] 2023-07-23 13:39
Decky doesn't really support non-steamos distros, and hasn't really been tested outside of arch, but I'll try to help anyway. Could you send the output of the CLI installer?

**Comment by PartyWumpus** [comment] 2023-07-23 15:54
Also, does the `~/homebrew` directory exist? It should have a services folder with the PluginLoader binary in. You could manually add the service if you want, you can see what the script is supposed to do here: https://github.com/SteamDeckHomebrew/decky-installer/blob/main/cli/install_release.sh

**Comment by AlphaCraft9658** [comment] 2023-07-23 19:05
This is the output of the installer
```
Deck user not found. Continuing anyway, as it probably just means user is on a non-steamos system.

[sudo] Passwort für alpha-craft: 
[sudo] Passwort für alpha-craft: 

GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
/tmp/user_install_script.sh: Zeile 9: 17987 Speicherzugriffsfehler  (Speicherabzug geschrieben) zenity "$@" 2> >(grep -v 'Gtk' 1>&2)
```
The homebrew folder does exist and has the service binary is inside of it.

**Comment by AlphaCraft9658** [comment] 2023-07-23 20:23
> This is the output of the installer
> 
> ```
> Deck user not found. Continuing anyway, as it probably just means user is on a non-steamos system.
> 
> [sudo] Passwort für alpha-craft: 
> [sudo] Passwort für alpha-craft: 
> 
> GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
> /tmp/user_install_script.sh: Zeile 9: 17987 Speicherzugriffsfehler  (Speicherabzug geschrieben) zenity "$@" 2> >(grep -v 'Gtk' 1>&2)
> ```
> 
> The homebrew folder does exist and has the service binary is inside of it.

So basically, the script fails at line 9. It tries disabling unnecessary warnings and doesn't complete the installation.

**Comment by PartyWumpus** [comment] 2023-07-23 20:24
right yeah that's why I said to use the CLI one

**Comment by AlphaCraft9658** [comment] 2023-07-24 12:05
> right yeah that's why I said to use the CLI one, not the .desktop file

The output of the cli installer:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  3413  100  3413    0     0  11296      0 --:--:-- --:--:-- --:--:-- 11296
Installing Steam Deck Plugin Loader release...
Installing version v2.10.3...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 20.6M  100 20.6M    0     0  15.7M      0  0:00:01  0:00:01 --:--:-- 26.2M
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   421  100   421    0     0   5606      0 --:--:-- --:--:-- --:--:--  5689
Grabbed latest release service.
Created symlink /etc/systemd/system/multi-user.target.wants/plugin_loader.service → /etc/systemd/system/plugin_loader.service.
```
It does create the service, but the service fails to start. When trying to start it manually, it crashes/doesn't start successfully (output of `sudo systemctl status plugin_loader`):
```
× plugin_loader.service - SteamDeck Plugin Loader
     Loaded: loaded (/etc/systemd/system/plugin_loader.service; enabled; preset: disabled)
    Drop-In: /usr/lib/systemd/system/service.d
             └─10-timeout-abort.conf
     Active: failed (Result: exit-code) since Mon 2023-07-24 14:04:26 CEST; 31s ago
   Duration: 496us
    Process: 13731 ExecStart=/home/alpha-craft/homebrew/services/PluginLoader (code=exited, status=203/EXEC)
   Main PID: 13731 (code=exited, status=203/EXEC)
        CPU: 571us

Jul 24 14:04:26 alpha-craft-Fedora systemd[1]: plugin_loader.service: Scheduled restart job, restart counter is at 5.
Jul 24 14:04:26 alpha-craft-Fedora systemd[1]: Stopped plugin_loader.service - SteamDeck Plugin Loader.
Jul 24 14:04:26 alpha-craft-Fedora systemd[1]: plugin_loader.service: Start request repeated too quickly.
Jul 24 14:04:26 alpha-craft-Fedora systemd[1]: plugin_loader.service: Failed with result 'exit-code'.
Jul 24 14:04:26 alpha-craft-Fedora systemd[1]: Failed to start plugin_loader.service - SteamDeck Plugin Loader.
```

**Comment by TrainDoctor** [comment] 2023-07-24 13:18
@AlphaCraft9658 is the binary marked as executable?

**Comment by AlphaCraft9658** [comment] 2023-07-24 13:19
> @AlphaCraft9658 is the binary marked as executable?

Yes. It is. I can run it manually and Decky Loader works, but I can't run it via systemctl with the service.

**Comment by NeilRuffell** [comment] 2023-07-29 02:59
I am also having this exact issue, same Fedora version and Steam release channel as OP.
I am able to manually launch the service.

On my machine the script file is owned by root. Is this on purpose or should permissions be changed in order to start automatically?

**Comment by AlphaCraft9658** [comment] 2023-07-29 06:03
> I am also having this exact issue, same Fedora version and Steam release channel as OP. I am able to manually launch the service.
> 
> On my machine the script file is owned by root. Is this on purpose or should permissions be changed in order to start automatically?
> 
> Edit: With the loader running correctly, I noticed I was unable to install any plugins because I did not have write access to the plugins folder. This was solved by adding write permissions. Could incorrect permissions be what is preventing the service from starting automatically?
> 
> Also it may be worth mentioning that this is not an issue of being unable to install decky-loader, but an issue of the service not starting at login.

There are no real issues with permissions. Maybe I might have to change the permissions for the binary, but everything else is working fine.

**Comment by NeilRuffell** [comment] 2023-07-29 07:02
I've just had some success here by copying PluginLoader out of the home directory and into /usr/share/bin/. After that, I updated the Plugin_Loader.service to reflect the new location, and then ran **systemctl daemon-reload**.
Rebooted Fedora and logged directly in to Gamescope-session, and the Decky icon was present without needing to start the service manually.

My knowledge is limited on this front, but I have read that systemd can have issues with running some services located under the /home directory.

Hope this helps @AlphaCraft9658

**Comment by PartyWumpus** [comment] 2023-07-29 07:48
I think the cause is probably fedora using SELinux. Once I merge #518 and make a prerelease, just giving decky the environment variable `DECKY_SELINUX` = `1` should make it work. You might need to run `sudo chcon -t bin_t $HOME/homebrew/services/PluginLoader` once as well. If you add the selinux bit through the service file, make sure to add `KEEP_SYSTEMD_SERVICE` = `0` so the service file isn't overwritten.

**Comment by AlphaCraft9658** [comment] 2023-07-29 16:47
Shouldn't it be KEEP_SYSTEMD_SERVICE=1? Or did I understand something
incorrectly?

Party Wumpus ***@***.***> schrieb am Sa., 29. Juli 2023,
09:49:

**Comment by PartyWumpus** [comment] 2023-07-29 16:48
> Shouldn't it be KEEP_SYSTEMD_SERVICE=1? Or did I understand something incorrectly?

Ah yep it should be 1. Sorry about that

**Comment by AlphaCraft9658** [comment] 2023-07-29 16:49
> I think the cause is probably fedora using SELinux. Once I merge #518 and make a prerelease, just giving decky the environment variable `DECKY_SELINUX` = `1` should make it work. You might need to run `sudo chcon -t bin_t $HOME/homebrew/services/PluginLoader` once as well. If you add the selinux bit through the service file, make sure to add `KEEP_SYSTEMD_SERVICE` = `0` so the service file isn't overwritten.

Shouldn't it be KEEP_SYSTEMD_SERVICE=1? Or did I understand something
incorrectly?

(I reposted this, because the formatting was incorrect.

**Comment by AlphaCraft9658** [comment] 2023-07-29 16:49
> > I think the cause is probably fedora using SELinux. Once I merge #518 and make a prerelease, just giving decky the environment variable `DECKY_SELINUX` = `1` should make it work. You might need to run `sudo chcon -t bin_t $HOME/homebrew/services/PluginLoader` once as well. If you add the selinux bit through the service file, make sure to add `KEEP_SYSTEMD_SERVICE` = `0` so the service file isn't overwritten.
> 
> Shouldn't it be KEEP_SYSTEMD_SERVICE=1? Or did I understand something
> incorrectly?
> 
> (I reposted this, because the formatting was incorrect.)

**Comment by AlphaCraft9658** [comment] 2023-07-29 16:50
> > Shouldn't it be KEEP_SYSTEMD_SERVICE=1? Or did I understand something incorrectly?
> 
> Ah yep it should be 1. Sorry about that 

It's okay. Good that this is clear now. Could it be possible to implement this into the service file automatically during setup, if needed? This could possibly be implemented in the future.

**Comment by PartyWumpus** [comment] 2023-07-29 16:54
> It's okay. Good that this is clear now. Could it be possible to implement this into the service file automatically during setup, if needed? This could possibly be implemented in the future.

Possibly, but support for systems beyond SteamOS isn't a priority, so might not happen any time soon. (basically I'll see if I can be bothered)

**Comment by NeilRuffell** [comment] 2023-07-29 17:00
At least a few more people may be able to get this going now. I really don't mind needing to do a bit of tinkering, it's how I've learned most of what I know about linux. Most solutions for what appeared to be the same issue were to ensure that the correct ports were not being tied up by something else, which is not the case here.

I imagine we will need to repeat this process after a decky-loader update or when swithcing between stable/prerelease. Did this end up working for you @AlphaCraft9658 ?
Thanks for the time on this @PartyWumpus

**Comment by PartyWumpus** [comment] 2023-07-29 17:09
> I imagine we will need to repeat this process after a decky-loader update or when switching between stable/prerelease. 
Should work fine forever if you set keep systemd to 1 and selinux to 1.

**Comment by NeilRuffell** [comment] 2023-07-29 17:11
Okay gotcha. So the PluginLpader can be updated without issue after setting that, good know.

**Comment by AlphaCraft9658** [comment] 2023-07-29 19:16
Has #518 been merged and pushed? If yes, is it available as a pre-release only or already as a stable release?

**Comment by PartyWumpus** [comment] 2023-07-29 19:43
> When will the fix be pushed to the stable-releade? Any ETA?

No eta, just whenever the next stable release comes out

**Comment by FanderWasTaken** [comment] 2023-08-09 22:41
Download [this file](https://github.com/SteamDeckHomebrew/decky-loader/files/12307385/install_release.txt), change `.txt` to `.sh` and run it with `sudo` to install Decky Loader until this is officially fixed. Run `sudo chcon -t bin_t $HOME/homebrew/services/PluginLoader` right after. In settings for it, set update channel to **Pre-release**.

Works on Fedora 38.

**Comment by AlphaCraft9658** [comment] 2023-08-10 16:00
> Download [this file](https://github.com/SteamDeckHomebrew/decky-loader/files/12307385/install_release.txt), change `.txt` to `.sh` and run it with `sudo` to install Decky Loader until this is officially fixed. Run `sudo chcon -t bin_t $HOME/homebrew/services/PluginLoader` right after. In settings for it, set update channel to **Pre-release**.
> 
> Works on Fedora 38.
> 
> 

I have installed the latest pre-release and I have manually edited the service file. It works fine now.

**Comment by PartyWumpus** [comment] 2023-08-28 14:50
This is now fixed in both the decky installer and decky itself. You should now be able to install as normal, and update like normal (although the fix is not yet in stable decky).

**Closed by PartyWumpus** 2023-08-28 14:50 UTC
Labels: bug
