### ISSUE TITLE
Edit order of plugins 

### ISSUE THREAD

**Issue by Martan404** [SteamDeckHomebrew/decky-loader#226] opened 2022-10-19 19:25 UTC
I don't like the way my plugins are organized by time of install. It would be nice if we could change it ourselves

**Comment by TrainDoctor** [comment] 2022-10-19 19:35
We're aware and working with a plugin developer to incorporate such functionality. This is a duplicate of discussion #175 but I'll leave it up and pin it so we don't get more duplicates.

**Comment by TrainDoctor** [comment] 2023-03-06 00:56
This will be closed by #378.

**Closed** 2023-04-06 20:12 UTC
Labels: help wanted, feature request
