### ISSUE TITLE
Store not loading

### ISSUE THREAD

**Issue by haven80** [SteamDeckHomebrew/decky-loader#156] opened 2022-08-27 23:29 UTC
I have tried to install latest prerelease. 
clicking on store icon does not load the plug-in’s download page. 
just spinning steam deck icon. 
with legacy version store load correctly.

**Comment by TrainDoctor** [comment] 2022-08-27 23:30
This is a duplicate of SteamDeckHomebrew/decky-plugin-store/issues/12

**Closed by TrainDoctor** 2022-08-27 23:30 UTC
