### ISSUE TITLE
[BUG] Plugins: Decky Loader doesn't instantiate and call plugin classes correctly

### ISSUE THREAD

**Issue by theCapypara** [SteamDeckHomebrew/decky-loader#509] opened 2023-07-19 18:18 UTC
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [X] I have attached logs to this bug report (failure to include logs will mean your issue will not be responded too).

### Bug Report Description

Plugins ship with a `main.py` that define a single Python class `Plugin`.

At the moment Decky doesn't actually instantiate that class, it just calls `_main` and `_unload` with the class itself as `self`, which is incorrect and leads to bugs and confusion when trying to interact with `self` inside `Plugin`. Most notably simple method calls like `self.method()` fail, complaining about `self` not being an instance of the object. The workaround for this is `Plugin.method(self)`, but this is pretty jank.

See: https://github.com/SteamDeckHomebrew/decky-loader/blob/6d086fb5d52a690c6e07c49ba065f1d83a8ab1db/backend/plugin.py#L90

### Expected Behaviour

Decky should just instantiate the Plugin class normally and call methods on it like on any other standard Python object. Alternatively, `_main` and `_unload` (and possibly any plugin method called by the frontend?) should be marked properly with `@classmethod`

### SteamOS version

n/a

### Selected Update Channel

Stable

### Have you modified the read-only filesystem at any point?

n/a

### Logs

n/a

**Comment by XanderXAJ** [comment] 2023-08-01 10:10
I've also come across this and I can confirm it is confusing. 😄 The current Plugin "class" is treated more like a module/namespace, so it's confusing when `self` doesn't always work as expected.

I'm currently working around it by making a separate class and instantiating that myself, treating Plugin like an API layer and moving all the "business logic" to the other class. This code is probably easier to understand and test, albeit it's also more verbose. Still, it doesn't take away from how confusing the Plugin's `self` can be!

# Possible fixes

If we're speculating on designs that would allow proper instantiation while remaining compatible, I'd consider adding a new static/class method where the plugin developer can return an instance of the plugin. This doesn't replace the existing `_main` etc. lifecycle methods.

Allowing the plugin developer to return an instance allows configuring the Plugin with parameters and provides inversion of control, making the Plugin code more easily testable.

For example:

```python
class Plugin:
    @staticmethod
    def instance() -> Plugin:
        # Plugin developer can grab configs needed for instantiating the plugin class here
        return Plugin()

    def __init__(self) -> None:
        # Plugin developer can perform whatever fast initialisation they need to here -- _main still exists for slower initialisation using asyncio
        pass
```

Decky Loader could pass in configuration to the `instance()` method, once again to allow the Plugin to be configured up front and make it more testable -- although the plugin author can pull that config out of `decky_plugin` to the same end.

Here are quick examples of all the configuration possibilities I've mentioned:

```python
# Loader could pass in lots of parameters...
class Plugin:
    @staticmethod
    def instance(plugin_path, bin_path, ...) -> Plugin:
        # Plugin developer can grab configs needed for instantiating the plugin class here
        return Plugin(plugin_path=plugin_path)

# ... But it might be more future proof to have a data class instead:
@dataclass
class PluginConfig:
    plugin_dir: Path
    runtime_dir: Path
    ... # Feel free to add more later -- it'll be backwards-compatible manner

class Plugin:
    @staticmethod
    def instance(config: PluginConfig) -> Plugin:
        # Plugin developer can grab configs needed for instantiating the plugin class here
        return Plugin(plugin_config=config)

# ... Or decky_plugin can continue to be used:
class Plugin:
    @staticmethod
    def instance() -> Plugin:
        # Plugin developer can grab configs needed for instantiating the plugin class here
        return Plugin(
            settings_dir=decky_plugin.DECKY_PLUGIN_SETTINGS_DIR,
            ...
        )
```

When it comes to loading the plugin, _potentially_ this could be as simple as detecting the presence of `instance` and using it if available:

https://github.com/SteamDeckHomebrew/decky-loader/blob/6d086fb5d52a690c6e07c49ba065f1d83a8ab1db/backend/plugin.py#L85C1-L85C40

```python
self.Plugin = module.Plugin
if hasattr(self.Plugin, "instance") and callable(self.Plugin.instance):
    self.Plugin = module.Plugin.instance(...)
```

However I can see a lot of manual passing of `self.Plugin` to Plugin methods (perhaps because of the lack of instantiation?), so it may not be quite as simple. Still, hopefully the idea comes across clearly.

**Comment by AAGaming00** [comment] 2024-05-14 12:59
fixed on websockets branch

**Closed** 2024-06-27 07:29 UTC
Labels: bug
