### ISSUE TITLE
[BUG] at the newest steampreview client,the plugin's ui does not display properly

### ISSUE THREAD

**Issue by pgs666** [SteamDeckHomebrew/decky-loader#385] opened 2023-02-26 13:59 UTC
### Please confirm

- [ ] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [X] I have attached logs to this bug report (failure to include logs will mean your issue will not be responded too).

### Bug Report Description

When I open the side panel and launch some plugin, the plugin ui doesn't look normal, like this
![](https://steamuserimages-a.akamaihd.net/ugc/2008079797114063325/020D50B671456E67EEFEE37961FFA9849E33F5E2/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false)
my decky-loader version is v2.6.1-pre2
![image](https://steamuserimages-a.akamaihd.net/ugc/2008079797114064270/A2CC46E4EB54C984F7C9C27CCBE65D9FB540B621/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false)
and my steam client version is 1677204767
![](https://steamuserimages-a.akamaihd.net/ugc/2008079797114076260/C1B35B7C6465E938483B27974EB8015B4712BEE7/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false)

### Expected Behaviour

it should be 

### SteamOS version

Steam OS 3.4.5 Preview

### Selected Update Channel

Prerelease

### Logs

[deckylog.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/10833840/deckylog.txt)

**Comment by TrainDoctor** [comment] 2023-02-26 16:31
Duplicate of #380.

**Closed by TrainDoctor** 2023-02-26 16:31 UTC
Labels: bug
