### ISSUE TITLE
Steam reboot loop since latest prerelease

### ISSUE THREAD

**Issue by nabel0** [SteamDeckHomebrew/decky-loader#244] opened 2022-11-01 08:00 UTC
Found a nasty bug on the latest decky prerelease, if you on Steam beta/preview.
If you restart the deck an stay on the login screen, steam is restarting after a while. 
After the 3rd Steam restart it automaticaly updates the steamclient to the stable one.
After this the loop is gone. 
If you login quick enough everything is fine afterwards.

Here is a video of the bug:

https://streamable.com/uvna12

**Comment by Pleasant-exe** [comment] 2022-11-02 23:15
I have this bug too.

**Comment by Pleasant-exe** [comment] 2022-11-02 23:17
I think animated boot causes it, it only happened when trying to download one.

**Comment by nabel0** [comment] 2022-11-03 06:58
> I think animated boot causes it, it only happened when trying to download one. 

The problem has nothing to do with the "Animation Changer" plugin. I'm not talking about the "Lock Screen", but the "Login Screen" if you have multiple Steam accounts set up on the deck. The "Animation Changer" plugin doesn't download anything at this point either. Did you watch my video about this problem? As you can see I don't use custom animation at all.

**Comment by albabe1** [comment] 2022-11-06 21:43
I am also getting this bug. Steam beta 3.3.2, Decky prerelease v2.3.2-pre1.

**Comment by TrainDoctor** [comment] 2022-11-06 21:47
@Pleasant-exe and @albabe1:
Steps to grab logs to help us diagnose the issue:
1. Reboot your deck fully (this is to clean up the logs that are grabbed)
2. Run ``cd ~`` to ensure you are located at ``/home/deck`` when running the next command.
3. Run ``journalctl -b0 -u plugin_loader.service > backend.log``, which will generate ``backend.log`` at ``/home/deck/backend.log``.
4. Grab the file and upload it to this thread.
Hopefully these will aid us in diagnosing the issue.

**Comment by nabel0** [comment] 2022-11-06 23:18
> @Pleasant-exe and @albabe1: Steps to grab logs to help us diagnose the issue:
> 
> 1. Reboot your deck fully (this is to clean up the logs that are grabbed).
> 2. Run `cd ~` to ensure you are located at `/home/deck` when running the next command.
> 3. Run `journalctl -b0 -u plugin_loader.service > backend.log`, which will generate `backend.log` at `/home/deck/backend.log`.
> 4. Grab the file and upload it to this thread.
>    Hopefully these will aid us in diagnosing the issue.

[backend.log](https://github.com/SteamDeckHomebrew/decky-loader/files/9947057/backend.log)

Attached is my logfile after 3 steam restarts in the "account selection" screen after I broke the loop and logged in.

**Comment by TrainDoctor** [comment] 2022-11-06 23:21
> Attached is my logfile after 3 steam restarts in the "account selection" screen after I broke the loop and logged in.

Ah, my mistake. I forgot that you said that this caused a bunch of restarts. Go ahead and grab the log without using ``-b0`` to grab the full log as that will be needed since the deck will reboot itself in this loop situation.

**Comment by nabel0** [comment] 2022-11-06 23:31
> > Attached is my logfile after 3 steam restarts in the "account selection" screen after I broke the loop and logged in.
> 
> Ah, my mistake. I forgot that you said that this caused a bunch of restarts. Go ahead and grab the log without using `-b0` to grab the full log as that will be needed since the deck will reboot itself in this loop situation.

Here you go


[backend.log](https://github.com/SteamDeckHomebrew/decky-loader/files/9947084/backend.log)

**Comment by albabe1** [comment] 2022-11-07 00:07
> 3\. journalctl -u plugin_loader.service > backend.log

Thanks. Mine: 
[backend.log](https://github.com/SteamDeckHomebrew/decky-loader/files/9947152/backend.log)

**Comment by TrainDoctor** [comment] 2022-11-13 02:55
Waiting on CEF logs due to core team being unable to replicate issue.

**Comment by TrainDoctor** [comment] 2022-11-13 03:09
@albabe1 @nabel0 please try to recreate the issue without any plugins on 2.4.0-pre1 (latest pre-release). If it occurs I have some steps to follow to grab the needed logs to debug the issue.

**Comment by TrainDoctor** [comment] 2022-11-13 22:55
Testing by @nabel0 yielded that the issue occurs when the SteamlessTimes plugin (and no others) is installed with Decky Loader.
@albabe1 tagging you to give you a heads up that the source of the issue has been found. Closing since the issue is not caused by Decky Loader itself. Link to relevant issue: https://github.com/EmuDeck/SteamlessTimes/issues/6

**Closed by TrainDoctor** 2022-11-13 22:55 UTC
Labels: bug
