### ISSUE TITLE
New Steam(OS?) Beta update kills Decky Quick Menu tile

### ISSUE THREAD

**Issue by subworx** [SteamDeckHomebrew/decky-loader#200] opened 2022-10-04 09:52 UTC
Steam released a Beta client today which enables custom boot animations.
Since this update, the decky icon no longer shows in the quick menu.
All modules remain in place and active, even update notifications pop up.

Rebooted several times, also re-ran the installer several times (thus automatically being on the latest preview) to no avail.

Possible cause: for the custom boot animations, Valve may have made changes to the library files where decky hooks in as well?

**Comment by TrainDoctor** [comment] 2022-10-04 13:02
Known issue, duplicate of https://github.com/SteamDeckHomebrew/decky-loader/issues/197.

Issue relates to the QAM and not to any change related to the boot files etc.

**Closed by TrainDoctor** 2022-10-04 13:02 UTC
