### ISSUE TITLE
[BUG] Decky Loader UI Does Not Appear In QAM After 5/9 Beta Client Update

### ISSUE THREAD

**Issue by wonderwallwoody** [SteamDeckHomebrew/decky-loader#448] opened 2023-05-10 02:42 UTC
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [X] I have attached logs to this bug report (failure to include logs will mean your issue will not be responded too).

### Bug Report Description

After updating to the newest beta client (5/9: https://store.steampowered.com/news/app/1675200/view/3717202826619866792?l=english), the UI no longer appears in the QAM. The loader service does seem to be running normally though (CSS Loader is active, the logs show Powertools and others running, etc.).

### Expected Behaviour

The Decky Loader Frontend available via QAM

### SteamOS version

SteamOS 3.4.6 (Beta Channel)

### Selected Update Channel

Prerelease

### Have you modified the read-only filesystem at any point?

No

### Logs

[deckylogs.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/11437567/deckylogs.txt)

**Comment by TrainDoctor** [comment] 2023-05-10 03:15
I know it's not efficient but could you use the CEF log menu to screenshot/pictures from boot to game-mode menu so we can see what is going wrong on the frontend side?

**Comment by wonderwallwoody** [comment] 2023-05-10 03:37
I'm not entirely sure if this is what's needed, but here's a picture of the tabs via CEF (it looks like the names are the same as the previous client version):
![Screenshot 2023-05-09 233103](https://github.com/SteamDeckHomebrew/decky-loader/assets/4131126/142c2352-f5d8-4f9d-862a-b8f1fc26c6c2)

Log-wise, the only one with any detail is SharedJSContext, attached below:
[sharedJSContext_Log.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/11437775/sharedJSContext_Log.txt)
This was after going back to stable client, reenabling the remote CEF forwarding, and then switching back to beta client. I'm not entirely sure how to intercept it at each stage (since it tends to not be visible in the inspector until after everything is up), but I can try to get a bit more detail in the morning if needed.

**Comment by ranger149** [comment] 2023-05-10 06:29
I can say I'm having the same issue. Going back to the stable SteamOS allows the Decky plugin to repopulate in QAM. Let me know if I can be of any assistance such as providing logs

**Comment by develroo** [comment] 2023-05-10 16:50
Have to say I found this the same today. I did check journald and saw a few plugins were broken. (auto night light and Deck battery)  but I manually removed them and restarted plugin_loader.service  and it runs but nothing shows up in the steam client even after a reboot. 

I do have to mention that each reboot causes a `Verfiying installation` message, which normally means it nobbled the plugins again.

**Comment by PartyWumpus** [comment] 2023-05-10 16:53
The cause issue has been found (it's [here](https://github.com/SteamDeckHomebrew/decky-frontend-lib/blob/8fb35e3c09fe6ec09c34a68e9c5af677aeb65ecf/src/deck-components/static-classes.ts#L462)) just needs to be fixed.

**Comment by develroo** [comment] 2023-05-10 16:56
> The cause of the issue has been found, (it's [here](https://github.com/SteamDeckHomebrew/decky-frontend-lib/blob/8fb35e3c09fe6ec09c34a68e9c5af677aeb65ecf/src/deck-components/static-classes.ts#L462)) it just needs to be fixed.

Hmm not sure I follow that, but is that the quick launch addon ? I did have that installed. Would removing it cause the plugins to reappear ?

**Comment by JohnnyBlocks** [comment] 2023-05-10 17:13
> Hmm not sure I follow that, but is that the quick launch addon ? I did have that installed. Would removing it cause the plugins to reappear ?

It's a CSS reference that must have changed with this beta update.   What it means is that the problem is acknowledged and understood but has not been changed yet but sit tight as they will get it sorted.

**Comment by RodoMa92** [comment] 2023-05-10 19:04
Fixed as soon as https://github.com/SteamDeckHomebrew/decky-frontend-lib/pull/83 is merged.

**Comment by PartyWumpus** [comment] 2023-05-10 21:24
The fix has made it to a prerelease (thanks @RodoMa92), so decky will now inject successfully in the beta steam client.
However, seemingly **all** of the plugins will need to bump DFL to continue working.

For now the easiest fix is probably to either revert to stable steamos OR if you wish to keep an OS feature from a later version, you can enable "show advanced update channels" in valve's Developer options, then in System settings set the "steam client update channel" to steam deck stable.

(picture of some of the broken plugins)
![image](https://github.com/SteamDeckHomebrew/decky-loader/assets/48649272/39fb6508-18df-4dcc-b84b-c0caaf2a8439)

**Comment by phush0** [comment] 2023-05-11 06:30
it works now but all plugins are broken

**Comment by RodoMa92** [comment] 2023-05-11 06:43
That's something expected since the base library is the one that broke. The plugins need to be manually updated, and that depends on all plugins developers, at least until plugins v2 rolls in.

**Comment by heapsprayer** [comment] 2023-05-11 08:28
I am not very experienced with React/JS but in order to avoid such issues in the future, is there a possibility for "dynamic linking" at runtime rather than static dependencies for the plugins?

**Comment by PartyWumpus** [comment] 2023-05-11 09:07
> I am not very experienced with React/JS but in order to avoid such issues in the future, is there a possibility for "dynamic linking" at runtime rather than static dependencies for the plugins?

Something like this is planned

**Comment by TrainDoctor** [comment] 2023-06-09 18:03
This has been resolved for a while, but has not been closed yet. Done.

**Closed by TrainDoctor** 2023-06-09 18:03 UTC
Labels: bug
