### ISSUE TITLE
[BUG] Decky-Loader not loading when switching accounts

### ISSUE THREAD

**Issue by mbtns** [SteamDeckHomebrew/decky-loader#673] opened 2024-08-08 12:06 UTC
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [X] I have attached logs to this bug report (failure to include logs will mean your issue may not be responded to).

### Bug Report Description

When I switch between Steam user accounts on Steam Deck, as well as on Fedora SIlverblue, Decky-loader is not loaded until a restart of the steam deck / Steam is performed. 

### Expected Behaviour

Decky-loader should be available after switching from account 1 to account 2

### SteamOS version

SteamOS 3.5.19 Stable / Fedora Silverblue

### Selected Update Channel

Stable

### Have you modified the read-only filesystem at any point?

No, flatpaks only

### Backend Logs

[deckylog.txt](https://github.com/user-attachments/files/16545821/deckylog.txt)

### Frontend Logs

[cef_log.previous.txt](https://github.com/user-attachments/files/16546259/cef_log.previous.txt)
[cef_log.txt](https://github.com/user-attachments/files/16546273/cef_log.txt)

**Comment by PartyWumpus** [comment] 2024-08-08 12:08
Duplicate of #618, fixed by #668

**Closed** 2024-08-08 12:09 UTC
Labels: bug

**Comment by mbtns** [comment] 2024-08-08 12:11
> Duplicate of #618, fixed by #668, just wait for it to reach stable (might take a while while we make sure 3.0 is as stable as can be)

Thanks. Only searched the open bug reports, will be more thorough next time.
