### ISSUE TITLE
[BUG] Decky Update Channel displays 'Prerelease' instead of 'Stable'

### ISSUE THREAD

**Issue by IngEyn** [SteamDeckHomebrew/decky-loader#415] opened 2023-04-04 17:06 UTC
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [X] I have attached logs to this bug report (failure to include logs will mean your issue will not be responded too).

### Bug Report Description

I've just installed Decky Loader for the first time on a new Steam Deck. I've followed all of the instructions carefully and have not encountered any issues during the installation or elsewhere.

The bug I'd like to report is that during the installation I've selected the 'Stable' channel for updates and it istalled version 2.4.6, which is the current stable Decky Loader release. However, when checking the Decky Loader settings in the quick-access menu of the Steam Deck, the update channel preset was set to 'Prerelease' instead of 'Stable'.

I do not think that it was actually set to 'Prerelease' though, as I've hit the 'Update' button right above the update channel setting and nothing changed as I had the latest version installed. I assume that it would have updated to the latest prerelease version if the update channel would have been set to 'Prerelease' so I think that it is just displaying the right channel but that's just an assumption.

### Expected Behaviour

The expected update channel would have been 'Stable' as I've set the installation to 'Stable' beforehand.

### SteamOS version

SteamOS 3.4.6 Stable

### Selected Update Channel

Stable

### Have you modified the read-only filesystem at any point?

No, I have never touched read-only files.

### Logs

Apr 04 18:15:45 steamdeck systemd[1]: Started SteamDeck Plugin Loader.
Apr 04 18:15:46 steamdeck PluginLoader[1176]: [loader][INFO]: plugin_path: /home/deck/homebrew/plugins
Apr 04 18:15:46 steamdeck PluginLoader[1176]: [loader][INFO]: import plugins from /home/deck/homebrew/plugins
Apr 04 18:15:46 steamdeck PluginLoader[1176]: [loader][INFO]: found plugin: protondb-decky
Apr 04 18:15:46 steamdeck PluginLoader[1176]: [loader][INFO]: Plugin ProtonDB Badges is passive
Apr 04 18:15:46 steamdeck PluginLoader[1176]: [loader][INFO]: Loaded ProtonDB Badges
Apr 04 18:15:56 steamdeck PluginLoader[1176]: [loader][INFO]: Hot reload enabled
Apr 04 18:16:06 steamdeck PluginLoader[1176]: [main][INFO]: Loading Decky frontend!
Apr 04 18:16:17 steamdeck PluginLoader[1176]: [updater][INFO]: Updated remote version information
Apr 04 19:06:56 steamdeck PluginLoader[1176]: [injector][WARNING]: The Tab SharedJSContext socket has been disconnected while listening for messages.
Apr 04 19:06:56 steamdeck PluginLoader[1176]: [main][INFO]: CEF has disconnected...

**Comment by beebls** [comment] 2023-04-04 22:24
Closing as duplicate of #393

**Closed** 2023-04-04 22:25 UTC
Labels: bug
