### ISSUE TITLE
Issue with beta client when selecting items in plug-in stores

### ISSUE THREAD

**Issue by XarceChronus** [SteamDeckHomebrew/decky-loader#252] opened 2022-11-12 03:59 UTC
This only affects client beta, going into a store such as animation changer or CSS loader and selecting an item causes an error overlay that blurs the entire screen.
You are unable to interact with it or refresh and it persists throughout the entire client unless you're in game.
Bringing up the steam menu Will bring back the blurry overlay error.
Using the three dots button is fine however and that menu seems to overlay everything beneath it.

**Comment by TrainDoctor** [comment] 2022-11-13 00:05
Since it was noted this issue effects not the Decky Loader's Plugin Store than this issue lies with the CSS-Loader Store and the Animation Changer stores respectively. I'll be closing this as a wontfix issue for now and would request that you please submit this as issues on each of their respective pages.
[CSS-Loader](https://github.com/suchmememanyskill/SDH-CssLoader) and [Animation Changer](https://github.com/TheLogicMaster/SDH-AnimationChanger) respectively.

**Closed by TrainDoctor** 2022-11-13 00:05 UTC
Labels: wontfix

**Comment by beebls** [comment] 2022-11-13 00:47
Despite being closed, I thought I'd still just chime in here as I make the frontend for CSSLoader.

This issue is caused by Valve changing how their router function is accessed. This was changed once a few weeks ago, to which we added a try-catch to use the new behaviour, but it appears that it has been changed _yet again_, so I will do some digging and try to figure out where the new-new router is located.
