### ISSUE TITLE
decky not present in steam ui

### ISSUE THREAD

**Issue by Seishirou101** [SteamDeckHomebrew/decky-loader#181] opened 2022-09-22 14:00 UTC
Hello, I have a similar issue to #126, but I'm unable to have decky load regardless of what I do.

I have already changed syncthing's port to 8384,
![1612-903-max](https://user-images.githubusercontent.com/57241064/191765284-df182242-a783-4d7c-8e02-61ecb0cb2417.png)

and uninstalled and reinstalled with and without sudo multiple times.

![1216-526-max](https://user-images.githubusercontent.com/57241064/191765709-0ae57c4f-b20d-4695-8643-7c7d68467d4c.png)
it looks like cef remote debugging lives on 8080 and I can access it on 127.0.0.1:8080

I don't know what else to try. Here is the information that was provided in #126 that I hope helps

`Linux steamdeck 5.13.0-valve21.1-1-neptune-02211-gc54cda5a36f3 #1 SMP PREEMPT Mon, 08 Aug 2022 22:27:56
+0000 x86_64 GNU/Linux`

```
Sep 22 08:27:59 steamdeck systemd[1]: Started SteamDeck Plugin Loader. 
Sep 22 08:28:00 steamdeck PluginLoader[4515]: main.py:63: DeprecationWarning: There is no current event loop 
Sep 22 08:28:00 steamdeck PluginLoader[4515]: [selector_events][DEBUG]: Using selector: EpollSelector 
Sep 22 08:28:00 steamdeck PluginLoader[4515]: [loader][INFO]: plugin_path: /home/deck/homebrew/plugins 
Sep 22 08:28:00 steamdeck PluginLoader[4515]: [updater][INFO]: /home/deck/homebrew/services 
Sep 22 08:28:00 steamdeck PluginLoader[4515]: [updater][DEBUG]: current branch: -1 
Sep 22 08:28:00 steamdeck PluginLoader[4515]: [updater][INFO]: Current branch is not set, determining branch from version... 
Sep 22 08:28:00 steamdeck PluginLoader[4515]: [updater][INFO]: Current version determined to be pre-release 
Sep 22 08:28:00 steamdeck PluginLoader[4515]: [inotifybuffer][DEBUG]: in-event <InotifyEvent: srcpath=b'/home/deck/homebrew/plugins', wd=1, mask=IN_ATTRI> 
Sep 22 08:28:00 steamdeck PluginLoader[4515]: [inotifybuffer][DEBUG]: in-event <InotifyEvent: srcpath=b'/home/deck/homebrew/plugins', wd=1, mask=IN_ATTRI> 
Sep 22 08:28:00 steamdeck PluginLoader[4515]: [loader][INFO]: import plugins from /home/deck/homebrew/plugins 
Sep 22 08:28:30 steamdeck PluginLoader[4515]: [updater][DEBUG]: checking for updates 
Sep 22 08:28:30 steamdeck PluginLoader[4515]: [updater][DEBUG]: current branch: -1 
Sep 22 08:28:30 steamdeck PluginLoader[4515]: [updater][INFO]: Current branch is not set, determining branch from version... 
Sep 22 08:28:30 steamdeck PluginLoader[4515]: [updater][INFO]: Current version determined to be pre-release 
Sep 22 08:28:30 steamdeck PluginLoader[4515]: [updater][DEBUG]: determining release type to find, branch is 1 
Sep 22 08:28:30 steamdeck PluginLoader[4515]: [updater][DEBUG]: release type: pre-release 
Sep 22 08:28:30 steamdeck PluginLoader[4515]: [updater][INFO]: Updated remote version information 
Sep 22 08:29:29 steamdeck PluginLoader[4515]: [main][INFO]: Plugin loader isn't present in Steam anymore, reinjecting... 
Sep 22 08:29:29 steamdeck PluginLoader[4515]: [main][INFO]: Failed to inject JavaScript into tab 
Sep 22 08:29:29 steamdeck PluginLoader[4515]: Traceback (most recent call last): 
Sep 22 08:29:29 steamdeck PluginLoader[4515]:   File "main.py", line 127, in inject_javascript 
Sep 22 08:29:29 steamdeck PluginLoader[4515]:   File "injector.py", line 91, in injecttotab 
Sep 22 08:29:29 steamdeck PluginLoader[4515]:   File "injector.py", line 87, in get_tab 
Sep 22 08:29:29 steamdeck PluginLoader[4515]: ValueError: Tab SP not found 
Sep 22 08:29:34 steamdeck PluginLoader[4515]: [injector][DEBUG]: ClientConnectorError excepted. 
Sep 22 08:29:34 steamdeck PluginLoader[4515]: [injector][DEBUG]: Steam isn't available yet. Wait for a moment... 
Sep 22 08:29:34 steamdeck PluginLoader[4515]: [injector][ERROR]: Traceback (most recent call last): 
Sep 22 08:29:34 steamdeck PluginLoader[4515]:   File "aiohttp/connector.py", line 986, in wrapcreate_connection 
Sep 22 08:29:34 steamdeck PluginLoader[4515]:   File "asyncio/baseevents.py", line 1064, in createconnection 
Sep 22 08:29:34 steamdeck PluginLoader[4515]:   File "asyncio/baseevents.py", line 1049, in createconnection 
Sep 22 08:29:34 steamdeck PluginLoader[4515]:   File "asyncio/baseevents.py", line 960, in connect_sock 
Sep 22 08:29:34 steamdeck PluginLoader[4515]:   File "asyncio/selectorevents.py", line 500, in sockconnect 
Sep 22 08:29:34 steamdeck PluginLoader[4515]:   File "asyncio/selectorevents.py", line 535, in sockconnectcb 
Sep 22 08:29:34 steamdeck PluginLoader[4515]: ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 8080) 
Sep 22 08:29:34 steamdeck PluginLoader[4515]: The above exception was the direct cause of the following exception: 
Sep 22 08:29:34 steamdeck PluginLoader[4515]: Traceback (most recent call last): 
Sep 22 08:29:34 steamdeck PluginLoader[4515]:   File "injector.py", line 68, in get_tabs 
Sep 22 08:29:34 steamdeck PluginLoader[4515]:   File "aiohttp/client.py", line 535, in _request 
Sep 22 08:29:34 steamdeck PluginLoader[4515]:   File "aiohttp/connector.py", line 542, in connect 
Sep 22 08:29:34 steamdeck PluginLoader[4515]:   File "aiohttp/connector.py", line 907, in createconnection 
Sep 22 08:29:34 steamdeck PluginLoader[4515]:   File "aiohttp/connector.py", line 1206, in createdirect_connection 
Sep 22 08:29:34 steamdeck PluginLoader[4515]:   File "aiohttp/connector.py", line 1175, in createdirect_connection 
Sep 22 08:29:34 steamdeck PluginLoader[4515]:   File "aiohttp/connector.py", line 992, in wrapcreate_connection 
Sep 22 08:29:34 steamdeck PluginLoader[4515]: aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:8080 ssl:default [Connect ca> 
Sep 22 08:29:39 steamdeck PluginLoader[4515]: [injector][DEBUG]: ClientConnectorError excepted. 
Sep 22 08:29:39 steamdeck PluginLoader[4515]: [injector][DEBUG]: Steam isn't available yet. Wait for a moment... 
Sep 22 08:29:39 steamdeck PluginLoader[4515]: [injector][ERROR]: Traceback (most recent call last): 
Sep 22 08:29:39 steamdeck PluginLoader[4515]:   File "aiohttp/connector.py", line 986, in wrapcreate_connection 
Sep 22 08:29:39 steamdeck PluginLoader[4515]:   File "asyncio/baseevents.py", line 1064, in createconnection 
Sep 22 08:29:39 steamdeck PluginLoader[4515]:   File "asyncio/baseevents.py", line 1049, in createconnection 
Sep 22 08:29:39 steamdeck PluginLoader[4515]:   File "asyncio/baseevents.py", line 960, in connect_sock 
Sep 22 08:29:39 steamdeck PluginLoader[4515]:   File "asyncio/selectorevents.py", line 500, in sockconnect 
Sep 22 08:29:39 steamdeck PluginLoader[4515]:   File "asyncio/selectorevents.py", line 535, in sockconnectcb 
Sep 22 08:29:39 steamdeck PluginLoader[4515]: ConnectionRefusedError: [Errno 111] Connect call failed ('::1', 8080, 0, 0) 
Sep 22 08:29:39 steamdeck PluginLoader[4515]: The above exception was the direct cause of the following exception: 
Sep 22 08:29:39 steamdeck PluginLoader[4515]: Traceback (most recent call last): 
Sep 22 08:29:39 steamdeck PluginLoader[4515]:   File "injector.py", line 68, in get_tabs 
Sep 22 08:29:39 steamdeck PluginLoader[4515]:   File "aiohttp/client.py", line 535, in _request 
Sep 22 08:29:39 steamdeck PluginLoader[4515]:   File "aiohttp/connector.py", line 542, in connect 
Sep 22 08:29:39 steamdeck PluginLoader[4515]:   File "aiohttp/connector.py", line 907, in createconnection 
Sep 22 08:29:39 steamdeck PluginLoader[4515]:   File "aiohttp/connector.py", line 1206, in createdirect_connection 
Sep 22 08:29:39 steamdeck PluginLoader[4515]:   File "aiohttp/connector.py", line 1175, in createdirect_connection 
Sep 22 08:29:39 steamdeck PluginLoader[4515]:   File "aiohttp/connector.py", line 992, in wrapcreate_connection 
Sep 22 08:29:39 steamdeck PluginLoader[4515]: aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:8080 ssl:default [Connect ca> 
Sep 22 08:29:44 steamdeck PluginLoader[4515]: [main][INFO]: Plugin loader isn't present in Steam anymore, reinjecting... 
Sep 22 08:29:59 steamdeck PluginLoader[4515]: [injector][DEBUG]: ClientConnectorError excepted. 
Sep 22 08:29:59 steamdeck PluginLoader[4515]: [injector][DEBUG]: Steam isn't available yet. Wait for a moment... 
Sep 22 08:29:59 steamdeck PluginLoader[4515]: [injector][ERROR]: Traceback (most recent call last): 
Sep 22 08:29:59 steamdeck PluginLoader[4515]:   File "aiohttp/connector.py", line 986, in wrapcreate_connection 
Sep 22 08:29:59 steamdeck PluginLoader[4515]:   File "asyncio/baseevents.py", line 1064, in createconnection 
Sep 22 08:29:59 steamdeck PluginLoader[4515]:   File "asyncio/baseevents.py", line 1049, in createconnection 
Sep 22 08:29:59 steamdeck PluginLoader[4515]:   File "asyncio/baseevents.py", line 960, in connect_sock 
Sep 22 08:29:59 steamdeck PluginLoader[4515]:   File "asyncio/selectorevents.py", line 500, in sockconnect 
Sep 22 08:29:59 steamdeck PluginLoader[4515]:   File "asyncio/selectorevents.py", line 535, in sockconnectcb 
Sep 22 08:29:59 steamdeck PluginLoader[4515]: ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 8080) 
Sep 22 08:29:59 steamdeck PluginLoader[4515]: The above exception was the direct cause of the following exception: 
Sep 22 08:29:59 steamdeck PluginLoader[4515]: Traceback (most recent call last): 
Sep 22 08:29:59 steamdeck PluginLoader[4515]:   File "injector.py", line 68, in get_tabs 
Sep 22 08:29:59 steamdeck PluginLoader[4515]:   File "aiohttp/client.py", line 535, in _request 
Sep 22 08:29:59 steamdeck PluginLoader[4515]:   File "aiohttp/connector.py", line 542, in connect 
Sep 22 08:29:59 steamdeck PluginLoader[4515]:   File "asyncio/baseevents.py", line 960, in connect_sock 
Sep 22 08:29:59 steamdeck PluginLoader[4515]:   File "asyncio/selectorevents.py", line 500, in sockconnect 
Sep 22 08:29:59 steamdeck PluginLoader[4515]:   File "asyncio/selectorevents.py", line 535, in sockconnectcb 
Sep 22 08:29:59 steamdeck PluginLoader[4515]: ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 8080) 
Sep 22 08:29:59 steamdeck PluginLoader[4515]: The above exception was the direct cause of the following exception: 
Sep 22 08:29:59 steamdeck PluginLoader[4515]: Traceback (most recent call last): 
Sep 22 08:29:59 steamdeck PluginLoader[4515]:   File "injector.py", line 68, in get_tabs 
Sep 22 08:29:59 steamdeck PluginLoader[4515]:   File "aiohttp/client.py", line 535, in _request 
Sep 22 08:29:59 steamdeck PluginLoader[4515]:   File "aiohttp/connector.py", line 542, in connect 
Sep 22 08:29:59 steamdeck PluginLoader[4515]:   File "aiohttp/connector.py", line 907, in createconnection 
Sep 22 08:29:59 steamdeck PluginLoader[4515]:   File "aiohttp/connector.py", line 1206, in createdirect_connection 
Sep 22 08:29:59 steamdeck PluginLoader[4515]:   File "aiohttp/connector.py", line 1175, in createdirect_connection 
Sep 22 08:29:59 steamdeck PluginLoader[4515]:   File "aiohttp/connector.py", line 992, in wrapcreate_connection 
Sep 22 08:29:59 steamdeck PluginLoader[4515]: aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:8080 ssl:default [Connect ca> 
Sep 22 08:30:04 steamdeck PluginLoader[4515]: [main][INFO]: Plugin loader isn't present in Steam anymore, reinjecting... 
Sep 22 08:30:04 steamdeck PluginLoader[4515]: [main][INFO]: Failed to inject JavaScript into tab 
Sep 22 08:30:04 steamdeck PluginLoader[4515]: Traceback (most recent call last): 
Sep 22 08:30:04 steamdeck PluginLoader[4515]:   File "main.py", line 127, in inject_javascript 
Sep 22 08:30:04 steamdeck PluginLoader[4515]:   File "injector.py", line 91, in injecttotab 
Sep 22 08:30:04 steamdeck PluginLoader[4515]:   File "injector.py", line 87, in get_tab 
Sep 22 08:30:04 steamdeck PluginLoader[4515]: ValueError: Tab SP not found 
Sep 22 08:30:09 steamdeck PluginLoader[4515]: [main][INFO]: Plugin loader isn't present in Steam anymore, reinjecting... 
Sep 22 08:30:09 steamdeck PluginLoader[4515]: [main][INFO]: Failed to inject JavaScript into tab 
Sep 22 08:30:09 steamdeck PluginLoader[4515]: Traceback (most recent call last): 
Sep 22 08:30:09 steamdeck PluginLoader[4515]:   File "main.py", line 127, in inject_javascript 
Sep 22 08:30:09 steamdeck PluginLoader[4515]:   File "injector.py", line 91, in injecttotab 
Sep 22 08:30:09 steamdeck PluginLoader[4515]:   File "injector.py", line 87, in get_tab 
Sep 22 08:30:09 steamdeck PluginLoader[4515]: ValueError: Tab SP not found 
Sep 22 08:30:15 steamdeck PluginLoader[4515]: [main][INFO]: Plugin loader isn't present in Steam anymore, reinjecting... 
Sep 22 08:30:15 steamdeck PluginLoader[4515]: [main][INFO]: Failed to inject JavaScript into tab 
Sep 22 08:30:15 steamdeck PluginLoader[4515]: Traceback (most recent call last): 
Sep 22 08:30:15 steamdeck PluginLoader[4515]:   File "main.py", line 127, in inject_javascript 
Sep 22 08:30:15 steamdeck PluginLoader[4515]:   File "injector.py", line 91, in injecttotab 
Sep 22 08:30:15 steamdeck PluginLoader[4515]:   File "injector.py", line 87, in get_tab 
Sep 22 08:30:15 steamdeck PluginLoader[4515]: ValueError: Tab SP not found 
Sep 22 08:30:20 steamdeck PluginLoader[4515]: [main][INFO]: Plugin loader isn't present in Steam anymore, reinjecting...
```

**Comment by PartyWumpus** [comment] 2022-09-22 14:53
Just to double check:
Do you have Crankshaft installed? It's not compatible with Decky.

**Comment by Seishirou101** [comment] 2022-09-22 15:49
No I do not have crankshaft installed

**Comment by TrainDoctor** [comment] 2022-09-22 17:03
Do you have syncthing or another service that would be using port 8080? That service needs to be disabled or have it's port changed as it's conflicting with 8080 (we cannot change this conflict, that port is required for the game-mode UI).

**Comment by PartyWumpus** [comment] 2022-09-22 18:24
I agree, I don't think it's likely anything else is using port 8080 if syncthing was working fine before.
I assume syncthing working fine now?

It seems to connect to the CEF debugger succesfully after 2 mins, and you're evenutally getting different errors to #126. It seems like it can't find the SP tab, which is weird... (not a dev, not certain about why that might happen although I do know that it is standard for it to happen a few times before successfully working)

You could try connecting to the CEF debugger while the game mode UI is open to see if CEF debugging is working properly? ('chrome://inspect/#devices' in chrome on another computer then press configure and add [steam deck IP addr]:8081 and [steam deck IP addr]:8080)
which should look like this:
![image](https://user-images.githubusercontent.com/48649272/191822716-a6f5dfa4-ef4d-493c-9620-930eebe79aa3.png)
![image](https://user-images.githubusercontent.com/48649272/191821942-b417e9e5-cee4-4635-9675-9db4c6ff9541.png)


(I would've checked that you're on the right version, but the log says you're on pre-release which is fine)

**Comment by Martmists-GH** [comment] 2022-09-22 18:53
> I agree, I don't think it's likely anything else is using port 8080 if syncthing was working fine before.

Just to be sure, can you run `lsof -i :8080` from a terminal and give us the output?

**Comment by Seishirou101** [comment] 2022-09-22 19:23
>I assume syncthing working fine now?

yes, works as normal after changing the port.

> (clearly it's working in desktop mode)?

i'm not sure how to check, but I can visit 127.0.0.1:8080 normally in desktop mode as the screenshot in the first post.

> You could try connecting to the CEF debugger while the game mode UI is open to see if CEF debugging is working properly in game mode

Well, this might be the problem, mine does not remotely look the same as your screenshot (if you were showing yourself connected to the steamdeck while in game mode ui. See below for screenshots just in case I did it incorrectly.

![374-437-max](https://user-images.githubusercontent.com/57241064/191832832-5dcf6d82-8d2d-4a23-9ea1-a5bd43ee641b.png)

![1134-1405-max](https://user-images.githubusercontent.com/57241064/191832811-9f307f95-e2d2-47a0-b9f9-1ea9d29b37cc.png)

IP address as shown by my switch just for clarification...
![1684-498-max](https://user-images.githubusercontent.com/57241064/191833142-66bce571-b037-4152-9116-8e4b1f9eef49.png)


> Just to be sure, can you run lsof -i :8080 from a terminal and give us the output?

I'm assuming you were asking me and not PartyWampus. Here is the output.
```
steamwebh 16241 deck   59u  IPv4 211993      0t0  TCP localhost:http-alt (LISTEN) 
steamwebh 16241 deck  107u  IPv4 211367      0t0  TCP localhost:http-alt->localhost:58812 (ESTABLISHED)
```

**Comment by Seishirou101** [comment] 2022-09-24 17:33
So, I installed crankshaft to see if something similar would work, and it appears in the menu like normal. I'll leave this up as the issue wasn't resolved unless y'all want it closed, but I'm no longer pursuing fixing it as I just wanted to install to mess with powertools

**Comment by TrainDoctor** [comment] 2022-09-24 17:36
> So, I installed crankshaft to see if something similar would work, and it appears in the menu like normal. I'll leave this up as the issue wasn't resolved unless y'all want it closed, but I'm no longer pursuing fixing it as I just wanted to install to mess with powertools

Crankshaft uses very destructive techniques but I'm happy that it works for you. In this case we couldn't identify the source of the issue for you. You are the only user I've helped with an issue like this that I couldn't identify the source of the issue.
I see no indication this exact failure state exists for other users, at least so far.

**Comment by Seishirou101** [comment] 2022-09-24 18:19
no worries, let me know if you'd like me to attempt something or close it since it may be sadly unique to my steamdeck as no one else can reproduce

**Comment by ItsRogueRen** [comment] 2022-09-28 15:56
I'm having this issue as well, and I've never had any sort of plugin thing installed on my Deck (only had it a week)

What terminal outputs would I need to share? I'm familiar with Linux overall.

**Comment by TrainDoctor** [comment] 2022-09-28 18:05
> I'm having this issue as well, and I've never had any sort of plugin thing installed on my Deck (only had it a week)
> 
> What terminal outputs would I need to share? I'm familiar with Linux overall, albeit Pop!_OS instead of Arch

You've verified CEF debugging is enabled? Trying a different route to see what can be done.

**Comment by TrainDoctor** [comment] 2022-09-28 20:55
> > > I'm having this issue as well, and I've never had any sort of plugin thing installed on my Deck (only had it a week)
> > > What terminal outputs would I need to share? I'm familiar with Linux overall, albeit Pop!_OS instead of Arch
> > 
> > 
> > You've verified CEF debugging is enabled? Trying a different route to see what can be done.
> 
> Yes, CEF Debugging is enabled, device rebooted after, then I ran the wget command. How would I change the route?

Hmm, the curl you mean? Check if when you paste it it turns ``|`` into ``>``.

```
curl -L https://github.com/SteamDeckHomebrew/decky-loader/raw/main/dist/install_prerelease.sh | sh
```

Here's the command just in case.

Also for logs please run:
``journalctl -b0 -u plugin_loader.service > loader.log``

**Comment by ItsRogueRen** [comment] 2022-09-28 21:16
here is the log file

file:///home/deck/loader.log

**Comment by TrainDoctor** [comment] 2022-09-28 21:27
> > > > > I'm having this issue as well, and I've never had any sort of plugin thing installed on my Deck (only had it a week)
> > > > > What terminal outputs would I need to share? I'm familiar with Linux overall, albeit Pop!_OS instead of Arch
> > > > 
> > > > 
> > > > You've verified CEF debugging is enabled? Trying a different route to see what can be done.
> > > 
> > > 
> > > Yes, CEF Debugging is enabled, device rebooted after, then I ran the wget command. How would I change the route?
> > 
> > 
> > Hmm, the curl you mean? Check if when you paste it it turns `|` into `>`.
> > ```
> > curl -L https://github.com/SteamDeckHomebrew/decky-loader/raw/main/dist/install_prerelease.sh | sh
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Here's the command just in case.
> > Also for logs please run: `journalctl -b0 -u plugin_loader.service > loader.log`
> 
> couldn't get the file to upload so here is a pastebin link: https://pastebin.com/iFcrS9PX

Why do they logs say Deckard plugin loader?

**Comment by ItsRogueRen** [comment] 2022-09-28 21:38
> > > > > > I'm having this issue as well, and I've never had any sort of plugin thing installed on my Deck (only had it a week)
> > > > > > What terminal outputs would I need to share? I'm familiar with Linux overall, albeit Pop!_OS instead of Arch
> > > > > 
> > > > > 
> > > > > You've verified CEF debugging is enabled? Trying a different route to see what can be done.
> > > > 
> > > > 
> > > > Yes, CEF Debugging is enabled, device rebooted after, then I ran the wget command. How would I change the route?
> > > 
> > > 
> > > Hmm, the curl you mean? Check if when you paste it it turns `|` into `>`.
> > > ```
> > > curl -L https://github.com/SteamDeckHomebrew/decky-loader/raw/main/dist/install_prerelease.sh | sh
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Here's the command just in case.
> > > Also for logs please run: `journalctl -b0 -u plugin_loader.service > loader.log`
> > 
> > couldn't get the file to upload so here is a pastebin link: https://pastebin.com/iFcrS9PX
> 
> Why do they logs say Deckard plugin loader?

Deckard is my user

**Comment by ItsRogueRen** [comment] 2022-09-29 01:40
> > > Why do they logs say Deckard plugin loader?
> > 
> > 
> > Deckard is my user
> 
> Last but certainly not least, give this a try for me `lsof -i :8080`

(1)(deck@Deckard ~)$ lsof -i :8080
COMMAND    PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
steamwebh 2880 deck   60u  IPv4  34362      0t0  TCP localhost:http-alt (LISTEN)
steamwebh 2880 deck  111u  IPv4  39113      0t0  TCP localhost:http-alt->localhost:55366 (ESTABLISHED)

**Comment by hyperwolf83** [comment] 2022-10-02 18:30
Hello all,
I've had the same issue for a while now and was unaware that decky required port 8080 to be open... here how I fixed my issue...
I do use syncthing on a regular basis and that is what was causing my issue of decky not showing in the steam deck ui.
To fix it I went to syncthing web UI, Clicked Actions -> Advanced -> GUI. I changed the port number under address field; this changes the the syncthing webui port number. I then restarted the steam deck, and ran the install command again for decky loader, and it has worked flawlessly since.  Just figured I would share my success here.

Cheers

**Comment by Reusable-Box** [comment] 2022-10-04 05:14
Sad to say I am having this issue now as well. I have also never used syncthing or anything that would occupy port 8080 on my deck. Tried toggling CEF debugging on/off with a coinciding re-install of decky but no dice.
[loader.log](https://github.com/SteamDeckHomebrew/decky-loader/files/9702949/loader.log)

To confirm this as well:
(deck@steamdeck ~)$ lsof -i :8080
COMMAND    PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
steamwebh 4071 deck   59u  IPv4  54535      0t0  TCP localhost:http-alt (LISTEN)
steamwebh 4071 deck   85u  IPv4  61922      0t0  TCP localhost:http-alt->localhost:47512 (ESTABLISHED)

**Comment by simon-hofmann** [comment] 2022-10-04 19:03
> Sad to say I am having this issue now as well. I have also never used syncthing or anything that would occupy port 8080 on my deck. Tried toggling CEF debugging on/off with a coinciding re-install of decky but no dice. [loader.log](https://github.com/SteamDeckHomebrew/decky-loader/files/9702949/loader.log)
> 
> To confirm this as well: (deck@steamdeck ~)$ lsof -i :8080 COMMAND PID USER FD TYPE DEVICE SIZE/OFF NODE NAME steamwebh 4071 deck 59u IPv4 54535 0t0 TCP localhost:http-alt (LISTEN) steamwebh 4071 deck 85u IPv4 61922 0t0 TCP localhost:http-alt->localhost:47512 (ESTABLISHED)
> 
> I did get a notification though that showed up in the gaming ui
> 
> ![7_20221003220837_1](https://user-images.githubusercontent.com/5264600/193740724-78e11fac-6519-4f53-a042-5c5b8dfe7d16.png)

I am having this issue now as well. I just get "Updates aviable for 1 plugin!" notification, thats it.

**Comment by PartyWumpus** [comment] 2022-10-04 19:06
@simon-hofmann Are you running preview/beta steam branch? there's currently a bug with decky on those branches, which has now been fixed. I would switch back to stable branch, then download the Decky update then you can switch back to the branch you were using

**Comment by Reusable-Box** [comment] 2022-10-04 19:18
Yep, all good for me now as well after swapping to stable, updating, and swapping back to beta. 

Think you can safely close the issue.

**Comment by TrainDoctor** [comment] 2022-10-04 19:29
> Yep, all good for me now as well after swapping to stable, updating, and swapping back to beta.
> 
> Think you can safely close the issue.

This issue itself is unrelated to the more recent one.

**Comment by ItsRogueRen** [comment] 2022-10-18 04:46
Also working here!

**Comment by TrainDoctor** [comment] 2022-10-18 04:49
> Also working here!

You're encountering the reported issue or are you saying it's been fixed for you.

**Comment by ItsRogueRen** [comment] 2022-10-21 02:52
> > Also working here!
> 
> You're encountering the reported issue or are you saying it's been fixed for you?

That its fixed and working

**Comment by sammccants** [comment] 2022-10-25 22:34
> @simon-hofmann Are you running preview/beta steam branch? there's currently a bug with decky on those branches, which has now been fixed. I would switch back to stable branch, then download the Decky update then you can switch back to the branch you were using

For me, the fix worked after downloading the Decky update, but once I switch Steam back to `beta` it was no longer showing again. Staying on `stable` for now 🤷

**Comment by alucryd** [comment] 2022-11-04 22:04
Adding myself to the list, confirmed decky doesn't work on the beta branch, even though CEF is running on 8080. Will have to stick to stable as well :/

**Comment by TrainDoctor** [comment] 2022-12-16 22:18
Just for the sake of it, can everyone involve in this thread give the latest decky pre-release (2.4.6-pre4) a try? A recent issue with decky not accounting for encodings other than US UTF8 (python issue) may be related to this issue.

**Comment by Reusable-Box** [comment] 2022-12-16 23:38
I have had 0 issues since following the steps given by simon-hofmann. Still on steam client beta. Decky has remained accessible in all versions since October for me., including what is now 2.4.6-pre5 as I write this.

**Comment by TrainDoctor** [comment] 2022-12-19 04:24
I believe that this has been resolved with the recent changes to account for non ASCII system locale. Sorry it took so long.

**Closed by TrainDoctor** 2022-12-19 04:24 UTC
Labels: bug, help wanted

**Comment by denis-g** [comment] 2023-05-30 15:10
Now I'm having some problems like this https://github.com/SteamDeckHomebrew/decky-loader/issues/181#issuecomment-1255454472
The latest beta Client and pre Decky and the latest stable Client and stable Decky - empty "Remote Target" list.

**Comment by PartyWumpus** [comment] 2023-05-30 15:13
> empty"Remote Target" list.

Is port 8080 being used by anything on your system?

**Comment by denis-g** [comment] 2023-05-30 15:34
@PartyWumpus No, 8080 and 8081 are not used.
On Deck lsof output:
```
COMMAND    PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
steamwebh 4202 deck   55u  IPv4  34626      0t0  TCP localhost:http-alt (LISTEN)
steamwebh 4202 deck  103u  IPv4  57743      0t0  TCP localhost:http-alt->localhost:33576 (ESTABLISHED)
steamwebh 4202 deck  132u  IPv4  62777      0t0  TCP localhost:http-alt->localhost:33646 (ESTABLISHED)
steamwebh 4202 deck  134u  IPv4  58761      0t0  TCP localhost:http-alt->localhost:33642 (ESTABLISHED)
steamwebh 4202 deck  143u  IPv4  69782      0t0  TCP localhost:http-alt->localhost:33742 (ESTABLISHED)
steamwebh 4202 deck  168u  IPv4  67456      0t0  TCP localhost:http-alt->localhost:33748 (ESTABLISHED)
```
