### ISSUE TITLE
[Request] toggle to disable a plugin

### ISSUE THREAD

**Issue by anyuzu99** [SteamDeckHomebrew/decky-loader#450] opened 2023-05-11 00:25 UTC
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] This is not a request for a plugin

### Feature Request Description

people may install a lot of plugins, but they may not use them all at once. they also want to get them back to work even offline, so we need a disable toggle.

**Comment by JohnnyCrazy** [comment] 2023-05-31 17:36
Duplicate of #350

**Closed by JohnnyCrazy** 2023-05-31 17:36 UTC
Labels: feature request
